### ISSUE TITLE
Active tile in sidebar

### ISSUE THREAD

**Issue by harshjohar** [harshjohar/fabchat#13]
The channel which is active should be highlighted in sidebar.

Currently it looks like this.
<img width="255" alt="Screenshot 2023-01-15 at 11 17 19 AM" src="https://user-images.githubusercontent.com/50266759/212524963-42c19355-0fce-4686-a6c8-11c1f98a4aa1.png">

**Comment by anshRS** [comment]
I am interested in resolving this issue

**Comment by anshRS** [comment]
I am interested in resolving this issue

**Comment by harshjohar** [comment]
@anshRS any update?

**Comment by anshRS** [comment]
Understood the basic flow of codebase
Working on it
Trying to integrate with firebase so as to test the fixes I have made
Just wanted to know whether I need to only update the environment file with required information to connect firebase with the app or do I need to make some other modifications too, especially for Firestore and Firebase storage services in the codebase

**Comment by anshRS** [comment]
@harshjohar

**Comment by anshRS** [comment]
Updates! @harshjohar 
The channel which is active is highlighted in channel bar
Now it looks like this
 
The general channel is active
![image](https://user-images.githubusercontent.com/114407607/216787320-39b4fafc-07dd-4234-b33a-3ee81a069522.png)

The coding-discussion channel is active
![image](https://user-images.githubusercontent.com/114407607/216787810-0d77764e-ee89-493d-a0fc-1268c1966151.png)


I’d like to hear your views on so that I may create a pull request for this issue

**Comment by harshjohar** [comment]
yes looks cool @anshRS , make pr

**Comment by harshjohar** [comment]
> 

oh so sorry,  i couldnt see the message on time. Is the problem fixed?
